substitutions:
  name: ""
  uname: ""
  project_name: "ntguest"
  project_version: "0.1"
  statuspin: GPIO5
  ssid: !secret ssid
  password: !secret password
  key: !secret apikey
  ota: !secret ota
  board: esp32dev, lolin_d32

esp32: 
  board: ${board}
  framework:
    type: arduino

esp32_ble_tracker:
bluetooth_proxy:

packages:
  remote_package:
    url: https://github.com/ntguest/esphome
    ref: main
    files:
      - templates/main.yaml
    refresh: 0s
