substitutions:
  name: ""
  uname: ""
  project_name: "ntguest"
  project_version: "0.1"
  statuspin: GPIO5
  ssid: !secret ssid
  password: !secret password
  key: !secret apikey
  ota: !secret ota
  board: esp32dev # lolin_d32 esp32-c3-devkitm-1

esp32: 
  board: ${board}
  framework:
    type: arduino # idf

esp32_ble_tracker:
bluetooth_proxy:

packages:
  remote_package:
    url: https://github.com/ntguest/esphome
    ref: main
    files:
      - templates/main.yaml # idf
    refresh: 0s

sensor:
  - platform: internal_temperature
    name: "Internal Temperature"
