substitutions:
  name: ""
  friendly_name: ""
  project_name: "ntguest"
  project_version: "0.1"
  statuspin: GPIO2

esp8266:
  board: d1_mini  # esp8285, 
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/ntguest/esphome    
    files: [/template.yaml]

