substitutions:
  name: ""
  friendly_name: ""
  project_name: "ntguest"
  project_version: "0.1"
  statuspin: GPIO2
  ssid: !secret ssid
  password: !secret password
  key: !secret apikey
  board: d1_mini  # esp8285, nodemcuv2

esp8266:
  board: ${board}
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/ntguest/esphome
    ref: main
    files:
      - templates/main.yaml
    refresh: 0s
