substitutions:
  devname: wt32
  uname: WT32
  dallaspin: GPIO2
  sdapin: GPIO14
  sclpin: GPIO4
  txpin: GPIO1
  rxpin: GPIO3
  electricitypin: GPIO35
  contactpin1: GPIO36
  pirpin1: GPIO39
  raindpin: GPIO33
  rainapin: GPIO32
  relaypin1: GPIO17

esphome:
  name: ${devname}
  friendly_name: ${uname}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apikey
  reboot_timeout: 0s

web_server:
  port: 80
  
ota:
  password: !secret password

ethernet:
  type: LAN8720
  mdc_pin: GPIO16
  mdio_pin: GPIO17
  clk_mode: GPIO0_IN
  phy_addr: 0
#  manual_ip:
#    static_ip: 192.168.xxx.xxx
#    gateway: 192.168.xxx.xxx
#    subnet: 255.255.255.0

time:
  - platform: sntp
    id: sntp_time
    timezone: UA

dallas:
  - pin: $dallaspin

i2c:
  sda: $sdapin
  scl: $sclpin
  scan: true
  id: i2c_a

uart:
  tx_pin: $txpin
  rx_pin: $rxpin
  baud_rate: 9600
  id: uart_a

button:
  - platform: restart
    name: "Restart"

  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset

binary_sensor:
  - platform: status
    name: "Status"

#  - platform: gpio
#    name: "Electricity"
#    id: el_a
#    pin: $electricitypin
#    device_class: "power"

#  - platform: gpio
#    name: "Contact 1"
#    id: cont_a
#    pin: $contactpin1
#    device_class: "door" # variants window

#  - platform: gpio
#    name: "Motion 1"
#    id: pir_a
#    pin: $pirpin1
#    device_class: "motion" # variants occupancy

#  - platform: gpio
#    name: "Rain"
#    id: rain_a
#    pin: $raindpin
#    device_class: "moisture" 

sensor:
  - platform: uptime
    name: "Uptime"
    device_class: "duration"

#  - platform: max44009
#    name: "Illuminance"
#    id: ill_a
#    address: 0x4A
#    device_class: "illuminance"

#  - platform: bme280
#    temperature:
#      name: "Temperature"
#      id: temp_a
#      oversampling: 16x
#    pressure:
#      name: "Pressure"
#      id: press_a
#    humidity:
#      name: "Humidity"
#      id: hum_a
#    address: 0x77 # variants 0x76
#    update_interval: 60s

#  - platform: dallas
#    address: 0x1c0000031edd2a28   # change it
#    name: "Outdoor Temperature"
#    id: temp_out_a

#  - platform: pzem004t
#    current:
#      name: "Current"
#      id: cur_a
#    voltage:
#      name: "Voltage"
#      id: volt_a
#    power:
#      name: "Power"
#      id: pow_a
#    energy:
#      name: "Energy"
#      id: en_a
#    update_interval: 60s

#  - platform: adc
#    pin: $rainapin
#    name: "Rain intensity"
#    id: rain_b
#    icon: mdi:weather-rainy
#    update_interval: 60s

switch:
#  - platform: gpio
#    name: "Relay 1"
#    id: relay_a
#    pin: $relaypin1
