sensor:
  - platform: homeassistant
    name: "sensor_home_assistant_1"
    entity_id: sensor.target_temperature_template
    id: sensor_home_assistant_1
    force_update: true
  - platform: template
    name: target_temperature_mean
    id: target_sensor_mean
    lambda: |-
      if (id(stat).state) {
        return (id(sensor_home_assistant_1).state);
      } else {
        return (id(sensor).state);
      }
    update_interval: 10s
