esphome:
  name: ${name}

wifi:
  ssid: ${ssid}
  password: ${password}
  reboot_timeout: 0s
  fast_connect: true

  ap:
    ssid: "${friendly_name} Hotspot"
    password: ${password}

captive_portal:

logger:
  baud_rate: 0

api:
  encryption:
    key: ${key}
  reboot_timeout: 0s

web_server:
  port: 80
  
ota:
  password: ${ota}

time:
  - platform: sntp
    id: sntp_time
    timezone: UA

status_led:
  pin:
    number: ${statuspin}
    inverted: True

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

sensor:
  - platform: wifi_signal
    name: "${friendly_name} WiFi Signal"
    icon: mdi:signal

  - platform: uptime
    name: "${friendly_name} Uptime"
    device_class: "duration"
    
button:
  - platform: restart
    name: "${friendly_name} Restart"

  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: Reset
