esphome:
  name: ${name}

wifi:
  ssid: ${ssid}
  password: ${password}
  reboot_timeout: 0s
  fast_connect: true

logger:
  baud_rate: 0
  
web_server:
  port: 80
  
ota:
  password: ${ota}

api:
  encryption:
    key: ${key}
  reboot_timeout: 0s
